import localFont from "next/font/local";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body className={``}>
                <div className="App px-10 md:px-16 xl:px-20 font-['Ubuntu',sans-serif] dark:bg-gray-900 dark:text-white">
                    <Navbar />
                    <div className="flex flex-col lg:flex-row lg:gap-10 xl:justify-between">
                        {children}
                    </div>
                    <Footer />
                </div>
            </body>
        </html>
    );
}
